# Etapa de build
FROM node:22-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install --legacy-peer-deps && npm run build -- --configuration production

# Etapa final: Nginx servindo Angular
FROM nginx:alpine
COPY --from=builder /app/dist/heat-map-app /usr/share/nginx/html