# Etapa de build
FROM node:18 AS builder
WORKDIR /app
COPY . .
RUN npm install && npm run build --prod

# Etapa final: Nginx servindo Angular
FROM nginx:alpine
COPY --from=builder /app/dist/heatMap-app /usr/share/nginx/html